# Data Cleaning and Analysis

In this notebook we are going to make some data cleaning and exploratory data analysis...

## EDA

First we are going to call some typical data analysis libraries.

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

Save the raw data as a `pandas.DataFrame` object.

In [8]:
raw_data = pd.read_csv('../data/Intelligent_Production_IIoT.csv')

In [9]:
raw_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 45 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   record_id                 15000 non-null  int64
 1   machine_id                15000 non-null  str
 2   production_line           15000 non-null  str
 3   batch_id                  15000 non-null  str
 4   shift                     15000 non-null  str
 5   product_type              15000 non-null  str
 6   ambient_temperature       14611 non-null  float64
 7   humidity                  14599 non-null  float64
 8   air_pressure              14620 non-null  float64
 9   ambient_vibration         15000 non-null  float64
 10  motor_temperature         14639 non-null  float64
 11  spindle_speed             14642 non-null  float64
 12  motor_current             14616 non-null  float64
 13  torque                    14613 non-null  float64
 14  vibration                 14611 non-null  float64
 15  acoustic_level            14628 non-null  float64
 16  bearing_temperature       14630 non-null  float64
 17  process_temperature       14604 non-null  float64
 18  hydraulic_pressure        14628 non-null  float64
 19  flow_rate                 14642 non-null  float64
 20  coolant_temperature       14659 non-null  float64
 21  material_feed_rate        14616 non-null  float64
 22  feed_pressure             14593 non-null  float64
 23  cycle_time                15000 non-null  float64
 24  throughput_rate           15000 non-null  float64
 25  production_volume         15000 non-null  float64
 26  machine_utilization       15000 non-null  float64
 27  resource_utilization      15000 non-null  float64
 28  operator_load             15000 non-null  float64
 29  power_consumption         15000 non-null  float64
 30  energy_per_unit           15000 non-null  float64
 31  defect_rate               15000 non-null  float64
 32  quality_score             15000 non-null  float64
 33  first_pass_yield          15000 non-null  float64
 34  fault_event_count         15000 non-null  int64
 35  downtime_minutes          15000 non-null  float64
 36  maintenance_frequency     15000 non-null  float64
 37  production_cost_per_unit  15000 non-null  float64
 38  resource_efficiency       15000 non-null  float64
 39  production_efficiency     15000 non-null  float64
 40  energy_saving_pct         15000 non-null  float64
 41  downtime_reduction_pct    15000 non-null  float64
 42  cost_reduction_pct        15000 non-null  float64
 43  benefit_score             15000 non-null  float64
 44  operation_mode            15000 non-null  str
dtypes: float64(37), int64(2), str(6)
memory usage: 5.1 MB

In [10]:
raw_data.keys()

Index(['record_id', 'machine_id', 'production_line', 'batch_id', 'shift',
       'product_type', 'ambient_temperature', 'humidity', 'air_pressure',
       'ambient_vibration', 'motor_temperature', 'spindle_speed',
       'motor_current', 'torque', 'vibration', 'acoustic_level',
       'bearing_temperature', 'process_temperature', 'hydraulic_pressure',
       'flow_rate', 'coolant_temperature', 'material_feed_rate',
       'feed_pressure', 'cycle_time', 'throughput_rate', 'production_volume',
       'machine_utilization', 'resource_utilization', 'operator_load',
       'power_consumption', 'energy_per_unit', 'defect_rate', 'quality_score',
       'first_pass_yield', 'fault_event_count', 'downtime_minutes',
       'maintenance_frequency', 'production_cost_per_unit',
       'resource_efficiency', 'production_efficiency', 'energy_saving_pct',
       'downtime_reduction_pct', 'cost_reduction_pct', 'benefit_score',
       'operation_mode'],
      dtype='str')

In [11]:
raw_data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
record_id,15000.0,7500.500000,4330.271354,1.000000,3750.750000,7500.500000,11250.250000,15000.000000
ambient_temperature,14611.0,24.520192,3.217158,15.000000,22.358616,24.548899,26.676740,35.000000
humidity,14599.0,55.002418,10.931021,25.000000,47.580498,55.097578,62.509889,85.000000
air_pressure,14620.0,101.297772,2.072980,96.000000,99.890961,101.319153,102.727663,106.000000
ambient_vibration,15000.0,0.348625,0.119128,0.050000,0.268181,0.349165,0.428356,0.800000
motor_temperature,14639.0,55.181107,5.036548,35.724116,51.784648,55.155338,58.520457,74.289639
spindle_speed,14642.0,2850.524255,423.660252,1500.000000,2559.811083,2851.862022,3135.629252,4000.000000
motor_current,14616.0,24.551220,2.790231,13.720123,22.652374,24.563339,26.471868,35.000000
torque,14613.0,53.090018,5.125547,32.059558,49.620896,53.067941,56.469878,72.608160
vibration,14611.0,1.288602,0.268465,0.238365,1.109383,1.287208,1.470908,2.264449
acoustic_level,14628.0,74.698778,4.397225,59.468260,71.702045,74.675991,77.627434,92.226050
bearing_temperature,14630.0,69.638637,4.490015,51.105215,66.633072,69.620888,72.659319,86.116076
process_temperature,14604.0,79.096056,5.049528,60.441266,75.717918,79.074689,82.454205,98.362417
hydraulic_pressure,14628.0,144.857776,17.889036,90.000000,132.696240,144.833126,157.036433,190.000000
flow_rate,14642.0,67.797916,5.298359,46.264863,64.174242,68.145201,72.096704,75.000000
coolant_temperature,14659.0,22.298056,2.560118,13.252179,20.588518,22.303839,24.003516,33.374523
material_feed_rate,14616.0,77.943481,13.982458,40.000000,68.438256,78.036717,87.587119,115.000000
feed_pressure,14593.0,79.106993,6.674017,50.999859,74.605166,79.126196,83.584622,100.000000
cycle_time,15000.0,32.099246,3.815783,20.000000,29.535842,32.113662,34.650093,47.157408
throughput_rate,15000.0,113.549796,8.075672,83.437338,108.094474,113.550883,119.083805,135.000000
production_volume,15000.0,111.726879,13.428791,74.357002,101.626838,111.205468,121.429494,150.000000
machine_utilization,15000.0,70.135073,5.080929,51.909127,66.655116,70.131180,73.565738,88.802601
resource_utilization,15000.0,85.465002,4.195072,70.388069,82.635608,85.487198,88.337655,99.000000
operator_load,15000.0,62.142525,13.913252,20.000000,52.646818,62.239390,71.619382,95.000000
power_consumption,15000.0,19.784479,1.731123,13.650633,18.609828,19.779331,20.961176,25.000000
energy_per_unit,15000.0,17.695554,1.743578,11.614161,16.284495,17.720944,19.349304,20.000000
defect_rate,15000.0,3.905590,0.744146,0.930878,3.413795,3.905891,4.412720,6.798653
quality_score,15000.0,87.714633,2.192741,78.303258,86.239108,87.675750,89.190007,97.504892
first_pass_yield,15000.0,93.131431,1.499806,87.436516,92.098884,93.121197,94.138597,98.848292
fault_event_count,15000.0,2.124667,1.457097,0.000000,1.000000,2.000000,3.000000,11.000000
downtime_minutes,15000.0,21.206501,6.734687,0.000000,16.577125,20.838395,25.563824,52.418677
maintenance_frequency,15000.0,2.440620,0.652707,0.103708,1.979126,2.404546,2.861697,5.497314
production_cost_per_unit,15000.0,8.122948,0.503077,5.985845,7.781991,8.125447,8.469348,10.331027
resource_efficiency,15000.0,98.964979,0.235137,94.130345,99.000000,99.000000,99.000000,99.000000
production_efficiency,15000.0,98.921282,0.518309,86.848255,99.000000,99.000000,99.000000,99.000000
energy_saving_pct,15000.0,5.524242,3.026324,2.000000,2.689714,5.122888,7.632844,19.370130
downtime_reduction_pct,15000.0,51.171643,8.573631,8.895835,45.568275,51.659942,57.209297,77.733525
cost_reduction_pct,15000.0,28.544505,2.774898,17.854688,26.685312,28.554980,30.386988,39.074997
benefit_score,15000.0,67.214111,1.191964,60.538675,66.454656,67.244797,68.027207,71.490604

In [12]:
raw_data.head(4)

,record_id,machine_id,production_line,batch_id,shift,product_type,ambient_temperature,humidity,air_pressure,ambient_vibration,...,downtime_minutes,maintenance_frequency,production_cost_per_unit,resource_efficiency,production_efficiency,energy_saving_pct,downtime_reduction_pct,cost_reduction_pct,benefit_score,operation_mode
0,1,M07,Line_A,B0343,Morning,Product_C,24.657935,69.272037,102.335679,0.366190,...,25.081059,2.172029,8.028928,99.0,99.0,9.364688,49.353148,26.199425,68.260235,High_Throughput
1,2,M20,Line_E,B0593,Afternoon,Product_D,15.953337,59.927354,100.055317,0.472410,...,20.400191,2.576074,8.537013,99.0,99.0,3.129223,56.434784,30.016525,68.491891,High_Throughput
2,3,M15,Line_E,B0205,Afternoon,Product_C,21.761215,44.487079,102.794636,0.478138,...,11.608597,2.357031,7.372440,99.0,99.0,6.433856,61.539859,33.412663,68.837230,Balanced_Production
3,4,M11,Line_B,B0993,Morning,Product_A,21.973528,59.022870,98.258859,0.417760,...,25.542778,2.840125,8.622625,99.0,99.0,3.284783,43.948708,34.699694,67.074754,Balanced_Production

In [13]:
raw_data['record_id'].describe()

count    15000.000000
mean      7500.500000
std       4330.271354
min          1.000000
25%       3750.750000
50%       7500.500000
75%      11250.250000
max      15000.000000
Name: record_id, dtype: float64

We note that the `production_id` its equal to the indexes, so we can drop it for now on.

In [14]:
raw_data.drop(labels='record_id', axis=1, inplace=True)

We want to divide the data in those with numeric-type and string-type columns. Lets start with the numerical-type ones.

In [38]:
data_numeric_only = raw_data.iloc[:, 5:-1]
data_numeric_only.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ambient_temperature       14611 non-null  float64
 1   humidity                  14599 non-null  float64
 2   air_pressure              14620 non-null  float64
 3   ambient_vibration         15000 non-null  float64
 4   motor_temperature         14639 non-null  float64
 5   spindle_speed             14642 non-null  float64
 6   motor_current             14616 non-null  float64
 7   torque                    14613 non-null  float64
 8   vibration                 14611 non-null  float64
 9   acoustic_level            14628 non-null  float64
 10  bearing_temperature       14630 non-null  float64
 11  process_temperature       14604 non-null  float64
 12  hydraulic_pressure        14628 non-null  float64
 13  flow_rate                 14642 non-null  float64
 14  coolant_temperature       14659 non-null  float64
 15  material_feed_rate        14616 non-null  float64
 16  feed_pressure             14593 non-null  float64
 17  cycle_time                15000 non-null  float64
 18  throughput_rate           15000 non-null  float64
 19  production_volume         15000 non-null  float64
 20  machine_utilization       15000 non-null  float64
 21  resource_utilization      15000 non-null  float64
 22  operator_load             15000 non-null  float64
 23  power_consumption         15000 non-null  float64
 24  energy_per_unit           15000 non-null  float64
 25  defect_rate               15000 non-null  float64
 26  quality_score             15000 non-null  float64
 27  first_pass_yield          15000 non-null  float64
 28  fault_event_count         15000 non-null  int64
 29  downtime_minutes          15000 non-null  float64
 30  maintenance_frequency     15000 non-null  float64
 31  production_cost_per_unit  15000 non-null  float64
 32  resource_efficiency       15000 non-null  float64
 33  production_efficiency     15000 non-null  float64
 34  energy_saving_pct         15000 non-null  float64
 35  downtime_reduction_pct    15000 non-null  float64
 36  cost_reduction_pct        15000 non-null  float64
 37  benefit_score             15000 non-null  float64
dtypes: float64(37), int64(1)
memory usage: 4.3 MB

In [39]:
data_numeric_only.head(4)

,ambient_temperature,humidity,air_pressure,ambient_vibration,motor_temperature,spindle_speed,motor_current,torque,vibration,acoustic_level,...,fault_event_count,downtime_minutes,maintenance_frequency,production_cost_per_unit,resource_efficiency,production_efficiency,energy_saving_pct,downtime_reduction_pct,cost_reduction_pct,benefit_score
0,24.657935,69.272037,102.335679,0.366190,52.965526,3076.599086,NaN,47.098043,0.999885,74.644949,...,2,25.081059,2.172029,8.028928,99.0,99.0,9.364688,49.353148,26.199425,68.260235
1,15.953337,59.927354,100.055317,0.472410,48.115477,3145.358704,25.715030,61.296107,1.302627,77.116641,...,2,20.400191,2.576074,8.537013,99.0,99.0,3.129223,56.434784,30.016525,68.491891
2,21.761215,44.487079,102.794636,0.478138,50.351004,2525.512002,27.553259,58.421784,0.836037,70.850881,...,0,11.608597,2.357031,7.372440,99.0,99.0,6.433856,61.539859,33.412663,68.837230
3,21.973528,59.022870,98.258859,0.417760,55.413848,3475.501288,27.879476,55.865708,1.514329,74.752200,...,3,25.542778,2.840125,8.622625,99.0,99.0,3.284783,43.948708,34.699694,67.074754

Now lets check info about the string-type columns.

In [16]:
data_str_only = raw_data.iloc[:, np.r_[0:5, -1]]
data_str_only

,machine_id,production_line,batch_id,shift,product_type,operation_mode
0,M07,Line_A,B0343,Morning,Product_C,High_Throughput
1,M20,Line_E,B0593,Afternoon,Product_D,High_Throughput
2,M15,Line_E,B0205,Afternoon,Product_C,Balanced_Production
3,M11,Line_B,B0993,Morning,Product_A,Balanced_Production
4,M08,Line_E,B0961,Night,Product_C,Precision_Quality
...,...,...,...,...,...,...
14995,M17,Line_E,B0950,Night,Product_B,Balanced_Production
14996,M18,Line_A,B0252,Afternoon,Product_D,Energy_Efficient
14997,M02,Line_C,B0162,Morning,Product_B,High_Throughput
14998,M03,Line_C,B0927,Night,Product_B,Balanced_Production
14999,M19,Line_D,B0110,Night,Product_A,Precision_Quality

In [17]:
data_str_only['machine_id'].sort_values().value_counts(sort=False)

machine_id
M01    729
M02    738
M03    745
M04    751
M05    735
M06    727
M07    743
M08    743
M09    722
M10    743
M11    684
M12    766
M13    816
M14    713
M15    798
M16    782
M17    812
M18    754
M19    750
M20    749
Name: count, dtype: int64

In [18]:
data_str_only['production_line'].sort_values().value_counts(sort=False)

production_line
Line_A    2982
Line_B    2964
Line_C    2947
Line_D    3024
Line_E    3083
Name: count, dtype: int64

In [19]:
data_str_only['batch_id'].sort_values().value_counts(sort=False)

batch_id
B0001    12
B0002    13
B0003    14
B0004    13
B0005    17
         ..
B0996    18
B0997    15
B0998    13
B0999    14
B1000    22
Name: count, Length: 1000, dtype: int64

In [20]:
data_str_only['shift'].value_counts()

shift
Morning      6039
Afternoon    5681
Night        3280
Name: count, dtype: int64

In [21]:
data_str_only['product_type'].sort_values().value_counts(sort=False)

product_type
Product_A    4464
Product_B    4224
Product_C    3645
Product_D    2667
Name: count, dtype: int64

In [22]:
data_str_only['operation_mode'].sort_values().value_counts(sort=False)

operation_mode
Balanced_Production    5250
Energy_Efficient       3750
High_Throughput        3000
Precision_Quality      3000
Name: count, dtype: int64

In [23]:
raw_data.head(3)

,machine_id,production_line,batch_id,shift,product_type,ambient_temperature,humidity,air_pressure,ambient_vibration,motor_temperature,...,downtime_minutes,maintenance_frequency,production_cost_per_unit,resource_efficiency,production_efficiency,energy_saving_pct,downtime_reduction_pct,cost_reduction_pct,benefit_score,operation_mode
0,M07,Line_A,B0343,Morning,Product_C,24.657935,69.272037,102.335679,0.366190,52.965526,...,25.081059,2.172029,8.028928,99.0,99.0,9.364688,49.353148,26.199425,68.260235,High_Throughput
1,M20,Line_E,B0593,Afternoon,Product_D,15.953337,59.927354,100.055317,0.472410,48.115477,...,20.400191,2.576074,8.537013,99.0,99.0,3.129223,56.434784,30.016525,68.491891,High_Throughput
2,M15,Line_E,B0205,Afternoon,Product_C,21.761215,44.487079,102.794636,0.478138,50.351004,...,11.608597,2.357031,7.372440,99.0,99.0,6.433856,61.539859,33.412663,68.837230,Balanced_Production

## Prediction of Production Cost

For this part we are going to study what are the principal variables that could relate within the `production_cost_per_unit` column.

In [40]:
prod_cost_corr = raw_data.corr(numeric_only=True)['production_cost_per_unit']
prod_cost_corr.apply(np.abs).sort_values(ascending=False).head(18)

production_cost_per_unit    1.000000
energy_per_unit             0.551343
benefit_score               0.504029
downtime_minutes            0.456741
downtime_reduction_pct      0.393300
energy_saving_pct           0.388550
production_volume           0.386450
fault_event_count           0.366931
cost_reduction_pct          0.301966
maintenance_frequency       0.297098
power_consumption           0.160502
vibration                   0.127505
motor_current               0.096526
production_efficiency       0.082307
spindle_speed               0.074952
resource_efficiency         0.060025
flow_rate                   0.053737
acoustic_level              0.047273
Name: production_cost_per_unit, dtype: float64

Then, we consider just this column for out machine learning training. For this, we define a function that determines if the correlation with the objective column is significant, then we create a *bool list* that will let us define the columns correlated.

In [41]:
def high_prod_cost_corr(col: pd.DataFrame):
    df = pd.DataFrame({'prod_cost':raw_data['production_cost_per_unit'],
                       'column': col})
    return bool(abs(df.corr(numeric_only=True).iloc[0, 1]) > 0.05)

bool_list = []

for name, column in data_numeric_only.items():
    correlated = high_prod_cost_corr(column)
    bool_list.append(correlated)

In [85]:
data_prod_cost_corr = data_numeric_only.iloc[:, bool_list]
data_prod_cost_corr.head(4)

,spindle_speed,motor_current,vibration,flow_rate,production_volume,power_consumption,energy_per_unit,fault_event_count,downtime_minutes,maintenance_frequency,production_cost_per_unit,resource_efficiency,production_efficiency,energy_saving_pct,downtime_reduction_pct,cost_reduction_pct,benefit_score
0,3076.599086,NaN,0.999885,69.302627,125.270994,20.156618,15.912526,2,25.081059,2.172029,8.028928,99.0,99.0,9.364688,49.353148,26.199425,68.260235
1,3145.358704,25.715030,1.302627,72.208857,104.791681,20.978039,19.945721,2,20.400191,2.576074,8.537013,99.0,99.0,3.129223,56.434784,30.016525,68.491891
2,2525.512002,27.553259,0.836037,61.199958,112.119319,18.877508,17.124998,0,11.608597,2.357031,7.372440,99.0,99.0,6.433856,61.539859,33.412663,68.837230
3,3475.501288,27.879476,1.514329,75.000000,104.885720,22.535570,20.000000,3,25.542778,2.840125,8.622625,99.0,99.0,3.284783,43.948708,34.699694,67.074754

Now, we can make a new DataFrame with this numerical info and some of the string-type ones. Lets remember the string DataFrame one.

In [86]:
data_str_only.head(4)

,machine_id,production_line,batch_id,shift,product_type,operation_mode
0,M07,Line_A,B0343,Morning,Product_C,High_Throughput
1,M20,Line_E,B0593,Afternoon,Product_D,High_Throughput
2,M15,Line_E,B0205,Afternoon,Product_C,Balanced_Production
3,M11,Line_B,B0993,Morning,Product_A,Balanced_Production

As `machine_id`, `production_line`, `batch_id` and `operation_mode` are only labels in the prodution chain supply, we can drop it and add the other 2 the previous DataFrame.

In [87]:
final_df = data_prod_cost_corr
final_df['shift'] = data_str_only['shift']
final_df['product_type'] = data_str_only['product_type']
final_df.head(4)

,spindle_speed,motor_current,vibration,flow_rate,production_volume,power_consumption,energy_per_unit,fault_event_count,downtime_minutes,maintenance_frequency,production_cost_per_unit,resource_efficiency,production_efficiency,energy_saving_pct,downtime_reduction_pct,cost_reduction_pct,benefit_score,shift,product_type
0,3076.599086,NaN,0.999885,69.302627,125.270994,20.156618,15.912526,2,25.081059,2.172029,8.028928,99.0,99.0,9.364688,49.353148,26.199425,68.260235,Morning,Product_C
1,3145.358704,25.715030,1.302627,72.208857,104.791681,20.978039,19.945721,2,20.400191,2.576074,8.537013,99.0,99.0,3.129223,56.434784,30.016525,68.491891,Afternoon,Product_D
2,2525.512002,27.553259,0.836037,61.199958,112.119319,18.877508,17.124998,0,11.608597,2.357031,7.372440,99.0,99.0,6.433856,61.539859,33.412663,68.837230,Afternoon,Product_C
3,3475.501288,27.879476,1.514329,75.000000,104.885720,22.535570,20.000000,3,25.542778,2.840125,8.622625,99.0,99.0,3.284783,43.948708,34.699694,67.074754,Morning,Product_A

## Dealing With Strings

The data we have collected seems to suit the need of our prediction. But, because we want to train a model with it, we must change all values to numerical values.

First, we are going to separate the feature columns and the objective column.

In [88]:
y = final_df['production_cost_per_unit']
X = final_df.drop('production_cost_per_unit', axis=1)

In the features DataFrame `X`, we are going to use the `get_dummies` function to convert the strings to numerical values.

In [89]:
X = pd.get_dummies(X, columns=['shift', 'product_type'], drop_first=False)
X

,spindle_speed,motor_current,vibration,flow_rate,production_volume,power_consumption,energy_per_unit,fault_event_count,downtime_minutes,maintenance_frequency,...,downtime_reduction_pct,cost_reduction_pct,benefit_score,shift_Afternoon,shift_Morning,shift_Night,product_type_Product_A,product_type_Product_B,product_type_Product_C,product_type_Product_D
0,3076.599086,NaN,0.999885,69.302627,125.270994,20.156618,15.912526,2,25.081059,2.172029,...,49.353148,26.199425,68.260235,False,True,False,False,False,True,False
1,3145.358704,25.715030,1.302627,72.208857,104.791681,20.978039,19.945721,2,20.400191,2.576074,...,56.434784,30.016525,68.491891,True,False,False,False,False,False,True
2,2525.512002,27.553259,0.836037,61.199958,112.119319,18.877508,17.124998,0,11.608597,2.357031,...,61.539859,33.412663,68.837230,True,False,False,False,False,True,False
3,3475.501288,27.879476,1.514329,75.000000,104.885720,22.535570,20.000000,3,25.542778,2.840125,...,43.948708,34.699694,67.074754,False,True,False,True,False,False,False
4,1968.506912,17.538344,1.321812,58.739215,100.686418,16.261478,15.823976,3,19.759181,3.410520,...,52.025084,31.553079,69.084109,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,2492.024403,22.224384,1.217624,59.364273,111.804352,17.313620,15.845521,1,16.902158,2.089719,...,53.536599,27.249614,66.523802,False,False,True,False,True,False,False
14996,3292.224452,26.401212,1.259283,75.000000,111.697261,22.344480,19.814678,3,30.318305,2.531326,...,40.716809,23.789906,64.651763,True,False,False,False,False,False,True
14997,3180.165182,28.490726,1.240818,71.981793,104.577444,20.564465,19.906823,1,18.501477,1.948076,...,55.964838,31.387269,68.383554,False,True,False,False,True,False,False
14998,2620.464558,23.066746,1.756963,66.415825,95.086684,18.577657,19.595452,1,18.139593,1.411668,...,59.098677,29.741537,67.243169,False,False,True,False,True,False,False
14999,3275.388811,27.433922,1.510103,70.789960,122.126642,20.716066,16.979564,2,15.934893,3.046104,...,56.693952,29.916539,68.018740,False,False,True,True,False,False,False

## Dealing With Null

Since we want this info to be trained, me need to fix the Null-type coordinates.

In [51]:
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   spindle_speed             14642 non-null  float64
 1   motor_current             14616 non-null  float64
 2   vibration                 14611 non-null  float64
 3   flow_rate                 14642 non-null  float64
 4   production_volume         15000 non-null  float64
 5   power_consumption         15000 non-null  float64
 6   energy_per_unit           15000 non-null  float64
 7   fault_event_count         15000 non-null  int64
 8   downtime_minutes          15000 non-null  float64
 9   maintenance_frequency     15000 non-null  float64
 10  production_cost_per_unit  15000 non-null  float64
 11  resource_efficiency       15000 non-null  float64
 12  production_efficiency     15000 non-null  float64
 13  energy_saving_pct         15000 non-null  float64
 14  downtime_reduction_pct    15000 non-null  float64
 15  cost_reduction_pct        15000 non-null  float64
 16  benefit_score             15000 non-null  float64
 17  shift                     15000 non-null  str
 18  operation_mode            15000 non-null  str
dtypes: float64(16), int64(1), str(2)
memory usage: 2.2 MB

Since all the Null spaces are in the numeric only columns,  we are going to replace them with their respective median.

In [92]:
X = X.fillna(X.median())
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   spindle_speed           15000 non-null  float64
 1   motor_current           15000 non-null  float64
 2   vibration               15000 non-null  float64
 3   flow_rate               15000 non-null  float64
 4   production_volume       15000 non-null  float64
 5   power_consumption       15000 non-null  float64
 6   energy_per_unit         15000 non-null  float64
 7   fault_event_count       15000 non-null  int64
 8   downtime_minutes        15000 non-null  float64
 9   maintenance_frequency   15000 non-null  float64
 10  resource_efficiency     15000 non-null  float64
 11  production_efficiency   15000 non-null  float64
 12  energy_saving_pct       15000 non-null  float64
 13  downtime_reduction_pct  15000 non-null  float64
 14  cost_reduction_pct      15000 non-null  float64
 15  benefit_score           15000 non-null  float64
 16  shift_Afternoon         15000 non-null  bool
 17  shift_Morning           15000 non-null  bool
 18  shift_Night             15000 non-null  bool
 19  product_type_Product_A  15000 non-null  bool
 20  product_type_Product_B  15000 non-null  bool
 21  product_type_Product_C  15000 non-null  bool
 22  product_type_Product_D  15000 non-null  bool
dtypes: bool(7), float64(15), int64(1)
memory usage: 1.9 MB

### Now the data is ready to develop our machine learning algorithm.